name: Convert Sigma rules
on:
  workflow_run:
    workflows: ["Validate Sigma rules"]
    types:
      - completed
#on:
#  push:
#    paths:
#      - "rules/**.yml"
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  convert-sigma-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install sigmatools
      - name: Giving the execution permission
        run: chmod +x tests/convert.sh
      - name: Convert Sigma rules
        run: tests/convert.sh
      - name: Commit files
        run: |
          git add ESRules
          git config --local user.email "hamid.bouhnik.it@gmail.com"
          git config --local user.name "NinnessOtu"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
